### ISSUE TITLE
Stuck in "Loading Visualizer"

### ISSUE THREAD

**Issue by radeonthe1st** [njm222/tessellator#40]
Hello,

Today I found out about this app, which I thought sounded amazing and wanted to give it a try. I logged in with my Spotify account, and then... nothing.

Page was stuck on "Loading Visualizer" for more than 10 minutes. Didn't count time exactly, but it might have been even 20 minutes and still no cool visualizing :(

I'm using a MacBook Pro M1 navigating via Firefox, if that helps.

Thanks in advance for your time.

**Comment by njm222** [comment]
Hello,

Thanks for checking out tessellator!

I think I know what is causing it. It is stuck on the "Loading Visualizer" screen because the app is unable to connect to the "Visualizer Player" automatically. I think some browsers have this as a security feature. Not 100% sure.

To resolve. Open up the spotify app on another device and if you change the device spotify is playing from to "Visualizer Player" it should start working and the "Loading Visualizer" will turn into a "Open Visualizer" button.

Apologies for the buggy app, I haven't had time to maintain it in over a year, but I do have a big v3 update in the works, here is a [preview](https://www.instagram.com/p/CZGQdCmJe5W/)

**Comment by njm222** [comment]
@radeonthe1st 

Just deployed an update that should resolve your issue:
https://tessellator-web.vercel.app/
